### ISSUE TITLE
Panorama's are blank

### ISSUE THREAD

**Issue by GrandmaPork** [suppergerrie2/PanoramaMod#14] opened 2024-06-13 23:03 UTC
I had a shader enabled and the panorama just was sky blue. I then disabled them and the same thing happened. I have distant horizons, oculus, and embeddium which might be causing this issue. I have ~180 mods in the modpack though so i can do a more in depth check if need be
![panorama_0](https://github.com/suppergerrie2/PanoramaMod/assets/109642282/a7dc1b35-89fe-4701-8c55-3841b1bfc81d)

**Comment by GrandmaPork** [comment] 2024-06-14 01:17
just downloaded and tested your latest update. no shaders works perfect now but using bliss, for example, doesn't seem to work. It also goes entirely black afterwards
![panorama_0](https://github.com/suppergerrie2/PanoramaMod/assets/109642282/22a569c6-daec-43ff-b48e-4510b9b1302e)

**Comment by suppergerrie2** [comment] 2024-06-14 07:09
What version are you using? Can you post a log file? 
Just to make sure. The new update works as long as no shader is enabled? 
What do you mean with it goes black afterwards?

**Comment by GrandmaPork** [comment] 2024-06-14 14:09
mc 1.20.1 panorama 1.5.2. forge 47.1.3. 
Pushing the screenshot button works unless a shader is enabled. 

https://github.com/suppergerrie2/PanoramaMod/assets/109642282/8818f050-fc1a-4123-aa3d-479a177e44c8



[latest.log](https://github.com/user-attachments/files/15839160/latest.log)

**Comment by Deepacat** [comment] 2024-07-06 19:12
Had this happen too, it's caused by either
Oculus (shaders weren't on)
Essential
or embeddium,
disabled all 3 and it was working

**Comment by GrandmaPork** [comment] 2024-07-06 19:45
essential isn't a cause. embeddium maybe. i havent had it happen with shaders turned off with oculus

**Comment by suppergerrie2** [comment] 2024-07-25 09:45
This is likely fixed in the latest version, but as the latest version is 1.20.5 and oculus does not seem to be available yet for that version I cannot verify this. I'll close this but feel free to open it if you can reproduce it with the latest version.

**Closed as completed by suppergerrie2** 2024-07-25 09:45 UTC

**Comment by SafeOfArsenal** [comment] 2024-08-09 10:58
hey could you please fix the panorama bug for 1.20.1?
